export const siteConfig = {
  name: "ZEN",
  fullName: "Zen Chinese Takeaway",
  tagline: "Fresh. Fast. Made in front of you.",
  description: "Fresh Chinese takeaway with open kitchen in Dennistoun, Glasgow. Rice included with every main dish. Cooked to order.",
  phone: "+44 141 556 1100",
  phoneDisplay: "0141 556 1100",
  address: { street: "618 Alexandra Parade", area: "Dennistoun", city: "Glasgow", postcode: "G31 3BT" },
  whatsapp: "441415561100",
  googleMapsEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2238.5!2d-4.2108!3d55.8608!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488846a5c5c5c5c5%3A0x1234567890abcdef!2s618%20Alexandra%20Parade%2C%20Glasgow%20G31%203BT!5e0!3m2!1sen!2suk",
  hours: "4pm to 11pm, 6 days (closed Tuesdays)",
  googleRating: 4.3,
  reviewCount: 97,
  facebook: "https://www.facebook.com/pages/Zen-Chinese-Takeaway/798098000361724",
  reviews: [
    { text: "Best salt and chilli chicken in the east end. Portions are massive and the price is right.", author: "Ryan M.", rating: 5 },
    { text: "Always fresh, always fast. You can see them cooking it right there. My go-to Chinese.", author: "Karen D.", rating: 5 },
    { text: "Proper Chinese takeaway. None of that soggy reheated stuff. Fresh every time.", author: "Steven G.", rating: 5 },
    { text: "Crispy duck is class. Rice comes with your meal which is a bonus. Sound staff too.", author: "Amy L.", rating: 5 },
    { text: "Moved to Dennistoun last year and this is hands down the best takeaway on the parade.", author: "Mark T.", rating: 5 },
    { text: "Food was delicious, reasonably priced, clean inside. Quick service and great flavour.", author: "Google Review", rating: 5 },
  ],
  menuHighlights: [
    { name: "Salt & Chilli Chicken", description: "Crispy battered chicken tossed with chillies, onions and peppers. Dry, spicy, addictive." },
    { name: "Crispy Aromatic Duck", description: "Slow-roasted, shredded with pancakes, spring onion, cucumber and hoisin." },
    { name: "Chicken Curry", description: "House curry sauce with tender chicken. Proper chippy-style, rice included." },
    { name: "Sweet & Sour King Prawn", description: "Battered king prawns in tangy sauce with peppers and pineapple." },
    { name: "Beef Chow Mein", description: "Wok-fried noodles with tender beef, beansprouts and spring onion." },
    { name: "Special Fried Rice", description: "Loaded with chicken, prawns, char siu pork and veg. A meal on its own." },
    { name: "Lemon Chicken", description: "Crispy fillets in sharp, glossy lemon sauce. Light, tangy, satisfying." },
    { name: "Salt & Chilli Chips", description: "Thick-cut chips with salt, chilli, garlic and spring onion." },
  ],
  features: [
    { title: "Cooked Fresh to Order", description: "Open kitchen. Watch your food being made right in front of you. Nothing sits around waiting. Every wok fired up fresh." },
    { title: "Rice Included", description: "Every main dish comes with rice. No hidden extras, no surprise charges at the till. What you see is what you pay." },
    { title: "Dennistoun's Favourite", description: "Generous portions, fair prices, and proper flavour. 97 Google reviews and counting. The locals keep coming back." },
  ],
};
