export const siteConfig = {
  name: "ZEN",
  fullName: "Zen Chinese Takeaway",
  tagline: "Fresh. Fast. Made in front of you.",
  description: "Fresh Chinese takeaway with open kitchen in Dennistoun, Glasgow. Rice included with every main dish. Cooked to order, 7 days a week.",
  phone: "+44 141 556 1100",
  phoneDisplay: "0141 556 1100",
  address: { street: "618 Alexandra Parade", area: "Dennistoun", city: "Glasgow", postcode: "G31 3BT" },
  whatsapp: "441415561100",
  googleMapsEmbed: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2238.5!2d-4.2108!3d55.8608!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x488846a5c5c5c5c5%3A0x1234567890abcdef!2s618%20Alexandra%20Parade%2C%20Glasgow%20G31%203BT!5e0!3m2!1sen!2suk",
  hours: "1pm to 11pm, 7 days",
  googleRating: 4.3,
  reviewCount: 87,
  reviews: [
    { text: "Best salt and chilli chicken in the east end. Portions are massive and the price is right.", author: "Ryan M.", rating: 5 },
    { text: "Always fresh, always fast. You can see them cooking it right there. My go-to Chinese.", author: "Karen D.", rating: 5 },
    { text: "Proper Chinese takeaway. None of that soggy reheated stuff. Fresh every time.", author: "Steven G.", rating: 5 },
    { text: "Crispy duck is class. Rice comes with your meal which is a bonus. Sound staff too.", author: "Amy L.", rating: 5 },
    { text: "Moved to Dennistoun last year and this is hands down the best takeaway on the parade.", author: "Mark T.", rating: 5 },
  ],
  menuHighlights: [
    { name: "Salt & Chilli Chicken", description: "Crispy battered chicken tossed with chillies, onions and peppers. Dry, spicy, addictive." },
    { name: "Crispy Aromatic Duck", description: "Slow-roasted duck, shredded at the table with pancakes, spring onion, cucumber and hoisin." },
    { name: "Chicken Curry", description: "Our house curry sauce with tender chicken pieces. Proper chippy-style curry, rice included." },
    { name: "Sweet & Sour King Prawn", description: "Battered king prawns in our tangy sweet and sour sauce with peppers and pineapple." },
    { name: "Beef Chow Mein", description: "Wok-fried noodles with tender beef, beansprouts and spring onion. A classic done right." },
    { name: "Special Fried Rice", description: "Egg fried rice loaded with chicken, prawns, char siu pork and vegetables. A meal on its own." },
    { name: "Lemon Chicken", description: "Crispy chicken fillets in a sharp, glossy lemon sauce. Light, tangy, and satisfying." },
    { name: "Salt & Chilli Chips", description: "Thick-cut chips tossed in salt, chilli, garlic and spring onion. The ultimate side." },
  ],
  features: [
    { title: "Cooked Fresh to Order", description: "Open kitchen. Watch your food being made right in front of you. Nothing sits around waiting." },
    { title: "Rice Included", description: "Every main dish comes with rice. No hidden extras, no surprise charges at the till." },
    { title: "Dennistoun's Favourite", description: "Generous portions, fair prices, and proper flavour. The locals keep coming back for a reason." },
  ],
  colors: {
    charcoal: "#1a1a1a",
    red: "#D63031",
    redHover: "#E84142",
    offWhite: "#F9F6F2",
    gold: "#C7A951",
  },
  seo: {
    title: "ZEN | Fresh Chinese Takeaway in Dennistoun, Glasgow",
    description: "Fresh Chinese food, cooked to order in our open kitchen. Rice included with every main. Dennistoun, Glasgow. Call 0141 556 1100.",
  },
};
